# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-07 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('utask', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='images',
        ),
        migrations.AddField(
            model_name='tasks',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(default='', upload_to='task', verbose_name='Путь до изображения'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tasks',
            name='complete',
            field=models.BooleanField(default=False, verbose_name='Выполнено'),
        ),
    ]
