# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-08 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utask', '0002_auto_20180407_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='image',
            field=models.ImageField(height_field='320', upload_to='task', width_field='240'),
        ),
    ]
