# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-08 06:09
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('utask', '0003_auto_20180408_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='upload', verbose_name='Путь до изображения'),
        ),
    ]
